#!/usr/bin/env python3
"""
Plotting script for Burgers' equation ROM comparison.

This script reads the CSV trajectories generated by the C++ burgers simulation
and creates a visualization comparing FOM vs ROM solutions at four time snapshots.
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os

def load_trajectory(filepath):
    """Load trajectory from CSV file."""
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found")
        return None

    data = np.genfromtxt(filepath, delimiter=',')
    return data

def main():
    # Define output directory
    output_dir = "output"

    # Load trajectories from output directory
    fom_traj = load_trajectory(os.path.join(output_dir, "fom_trajectory.csv"))
    default_rom_traj = load_trajectory(os.path.join(output_dir, "default_rom_trajectory.csv"))
    hypred_rom_traj = load_trajectory(os.path.join(output_dir, "hypred_rom_trajectory.csv"))

    if fom_traj is None:
        print("Error: Could not load FOM trajectory from output directory")
        sys.exit(1)

    # Select time indices for snapshots: early, mid, final
    num_timesteps = fom_traj.shape[0]
    time_indices = [
        num_timesteps // 3,                   # early
        2 * num_timesteps // 3,               # mid
        num_timesteps - 1                     # final
    ]
    time_labels = ["Early (t≈T/3)", "Mid (t≈2T/3)", "Final (t=T)"]

    # Create figure with 1x3 subplots (one for each time snapshot)
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle("1D Burgers' Equation: FOM vs ROM Solutions Over Time", fontsize=16, fontweight='bold')
    axes = axes.flatten()

    # Spatial coordinate array
    x_space = np.arange(fom_traj.shape[1])

    # Plot each time snapshot
    for plot_idx, (time_idx, time_label) in enumerate(zip(time_indices, time_labels)):
        ax = axes[plot_idx]

        # Extract states at this time index
        fom_state = fom_traj[time_idx, :]

        # Plot FOM solution
        ax.plot(x_space, fom_state, 'b-', linewidth=2.5, label='FOM', marker='o',
                markersize=3, markevery=8, zorder=3)

        # Plot default ROM if available and has this timestep
        if default_rom_traj is not None and time_idx < default_rom_traj.shape[0]:
            default_state = default_rom_traj[time_idx, :]
            ax.plot(x_space, default_state, 'r--', linewidth=2, label='Default Galerkin ROM',
                    marker='s', markersize=3, markevery=8, zorder=2)

            # Compute error
            default_error = np.linalg.norm(fom_state - default_state) / np.linalg.norm(fom_state)
        else:
            default_error = None

        # Plot hyperreduced ROM if available and has this timestep
        if hypred_rom_traj is not None and time_idx < hypred_rom_traj.shape[0]:
            hypred_state = hypred_rom_traj[time_idx, :]
            ax.plot(x_space, hypred_state, 'g-.', linewidth=2, label='Hyper-Reduced ROM',
                    marker='^', markersize=3, markevery=8, zorder=1)

            # Compute error
            hypred_error = np.linalg.norm(fom_state - hypred_state) / np.linalg.norm(fom_state)
        else:
            hypred_error = None

        # Format subplot
        ax.set_xlabel('Spatial Index', fontsize=10)
        ax.set_ylabel('Solution Value', fontsize=10)
        ax.set_title(f'{time_label}', fontsize=11, fontweight='bold')
        ax.legend(loc='best', fontsize=9)
        ax.grid(True, alpha=0.3)

        # Add error text if available
        error_text = ""
        if default_error is not None:
            error_text += f"ROM err: {default_error:.3e}\n"
        if hypred_error is not None:
            error_text += f"HR-ROM err: {hypred_error:.3e}"

        if error_text:
            ax.text(0.98, 0.05, error_text, transform=ax.transAxes,
                   fontsize=8, verticalalignment='bottom', horizontalalignment='right',
                   bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout()
    plt.savefig('burgers_rom_comparison.png', dpi=150, bbox_inches='tight')
    print("✓ Saved plot to burgers_rom_comparison.png")

    # Print summary statistics
    print("\n" + "="*60)
    print("TRAJECTORY SUMMARY")
    print("="*60)
    print(f"FOM trajectory shape: {fom_traj.shape}")
    if default_rom_traj is not None:
        print(f"Default ROM trajectory shape: {default_rom_traj.shape}")
    if hypred_rom_traj is not None:
        print(f"Hyper-Reduced ROM trajectory shape: {hypred_rom_traj.shape}")

    # Compute errors at final time
    fom_final = fom_traj[-1, :]

    if default_rom_traj is not None:
        default_final = default_rom_traj[-1, :]
        default_error = np.linalg.norm(fom_final - default_final) / np.linalg.norm(fom_final)
        print(f"\nFinal-time error (Default ROM vs FOM): {default_error:.6e}")

    if hypred_rom_traj is not None:
        hypred_final = hypred_rom_traj[-1, :]
        hypred_error = np.linalg.norm(fom_final - hypred_final) / np.linalg.norm(fom_final)
        print(f"Final-time error (Hyper-Reduced ROM vs FOM): {hypred_error:.6e}")

    print("="*60)

if __name__ == "__main__":
    main()
